version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    errcheck:
      check-type-assertions: false
      check-blank: false
    staticcheck:
      checks:
        - "all"
        - "-SA1019"
  exclusions:
    paths:
      - vendor$
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: test/
        linters:
          - errcheck
